# Generated by Django 4.0 on 2022-08-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picturename', models.CharField(blank=True, max_length=50, null=True, verbose_name='resim adı')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='başlık')),
                ('text', models.TextField(blank=True, null=True, verbose_name='mesaj')),
                ('postdate', models.DateTimeField(blank=True, null=True, verbose_name='yayınlanma tarihi')),
                ('column', models.IntegerField(verbose_name='sütun seçimi')),
            ],
        ),
    ]
