# Generated by Django 4.0 on 2022-08-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='column',
        ),
    ]
