# Generated by Django 4.0 on 2022-08-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_announcements_postdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='column',
            field=models.IntegerField(default=1, verbose_name='sütun seçimi'),
            preserve_default=False,
        ),
    ]
