# Generated by Django 4.1 on 2022-08-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_teammembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='teamdescribtion',
            field=models.TextField(blank=True, null=True, verbose_name='takım açıklaması'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='linkedin',
            field=models.CharField(max_length=50, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='role',
            field=models.CharField(choices=[('1', 'kaptan'), ('2', 'yazılım'), ('3', 'mekanik'), ('4', 'elektronik')], default='4', max_length=2, verbose_name='takımdaki rolü'),
        ),
    ]
