# Generated by Django 4.1 on 2022-08-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_teams_teamdescribtion_alter_teammembers_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='teamlogo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='resim adı'),
        ),
    ]
