# Generated by Django 4.1 on 2022-08-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_teams_teamlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='github'),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='insta'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İsim'),
        ),
    ]
