# Generated by Django 4.1 on 2022-08-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_teammembers_github_teammembers_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='resim adı'),
        ),
    ]
