# Generated by Django 4.1 on 2022-08-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_teammembers_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='takım rolü'),
        ),
    ]
