# Generated by Django 4.1 on 2022-08-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_teammembers_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bölüm'),
        ),
    ]
