# Generated by Django 4.1 on 2022-08-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_teammembers_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(blank=True, max_length=50, null=True, verbose_name='resim adı')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='İsim')),
                ('role', models.CharField(blank=True, max_length=50, null=True, verbose_name='Görev')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='bölüm')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='sınıf')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True, verbose_name='linkedin')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='insta')),
                ('display', models.IntegerField(verbose_name='gösterim sırası')),
            ],
        ),
    ]
