# Generated by Django 4.1 on 2022-09-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('PLATİN', 'Plat')], max_length=10, verbose_name='Sponsorluk seviyesi')),
                ('picture', models.CharField(blank=True, max_length=50, null=True, verbose_name='resim adı')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şirket adı')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Web sitesi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True, verbose_name='linkedin')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='insta')),
            ],
        ),
        migrations.AlterField(
            model_name='announcements',
            name='picturename',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='resim link'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='picture',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='resim link'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='resim link'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='teamlogo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='resim link'),
        ),
    ]
