# Generated by Django 4.1 on 2022-09-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_sponsors_alter_announcements_picturename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='slidercontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(blank=True, max_length=50, null=True, verbose_name='resim link')),
            ],
        ),
    ]
