# Generated by Django 4.1 on 2022-09-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_slidercontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slidercontent',
        ),
    ]
