# Generated by Django 4.1 on 2022-09-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_delete_slidercontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='insta'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='resim link'),
        ),
    ]
